name: Build

on:
  push:
    branches:
      - release

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      # - name: Build wheels
      #   uses: pypa/cibuildwheel@v2.3.1
      #   env:
      #     CIBW_SKIP: '*musllinux* pp*'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Update build tools
        run: |
         python -m pip install -U pip setuptools wheel

      - name: Build wheel
        run: |
         python -m pip wheel -w ./wheelhouse/ .

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/bposd*.whl

      - name: Install twine
        run: |
          python -m pip install -U twine
      
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.BPOSD_PYPI_PASSWORD }}
        run: |
          twine upload ./wheelhouse/bposd*whl

